### ISSUE TITLE
قابلیت اپدیت خودکار لینک ساب

### ISSUE THREAD

**Issue by yasbija** [hossein75rn/vpn#1]
سلام خوبین. دمتون گرمو. میگم اگه اینو بهش اضافه کنین خیلی خوب میشه همه میان سراغ این کارتون.....قابلیت اپدیت خودکار لینک ساب در برنامه v2rayng

**Comment by hossein75rn** [comment]
سلام چیزی که میگید شدنی هست ولی میتونید کانفیگ ها رو حالت ساب اضافه کنید و هر کدوم خراب شدش عوضش کنید و نیازی نیست که ساب بسازید اصلا اما اگر نیاز دارین تو آپدیت بعدی میزارمش

**Comment by yasbija** [comment]
مرسی که پاسخ دادین. نه منظورم برای مشتری هست ما کانفیگ رو عوض میکنیم منتها مشتری باید آپدیت رو بزنه تا براش کانفیگای جدید  بیاد. منتها همه ممکنه update subscription رو نزنن و یا یادشون بره ، این قابلیت خودکار تو برنامه باشه که مثلا  تنظیمش کنیم هر 3 ساعت به طور خودکار آپدیت رو بزنه.

**Comment by hossein75rn** [comment]
بعله میشه ولی راه بهترش اینه که هر موقع روی دکمه رفرش در صفحه اصلی زدن براشون ساب های جدید بیاد اگر برنامه رو ران کنین متوجه منظورم میشین

**Comment by hossein75rn** [comment]
سلام و ادب یه اپ تمیز تر و بهتر براتون آماده کردم به پروفایلم برید نوشته AnamisVpn  اون تمام این قابلیت ها رو داره
